apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-local-storage
provisioner: pd.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
